- name: Install gluster
  hosts: gluster_nodes
  become: true
  become_method: sudo
  vars_files:
    - ./vars/gluster.yml
  roles:
    - gluster-init
- name: Add gluster clients
  hosts: docker
  become: true
  become_method: sudo
  vars_files:
  - ./vars/gluster.yml
  roles:
  - gluster-add-clients
