---
- name: Update and Upgrade all Hosts && basic settings
  become: true
  become_method: sudo
  hosts: ubuntu
  roles:
     - host-settings
     - geerlingguy-ntp

- name: Install docker and dependencies
  become: true
  become_method: sudo
  hosts: docker
  vars_files:
    - ./vars/external.yml
  roles:
    - install-docker
    - change-docker-path-vol