- name: Verify Gluster dependencies
  apt:
    pkg:
      - xfsprogs
      - attr
      - glusterfs-common
      - glusterfs-client
    state: present
    force_apt_get: true
    update_cache: yes

- name: Create GlusterFS mount directory
  file:
    path: "/mnt/{{ gluster_volume_name }}"
    state: directory

- name: Mount GlusterFS volume
  mount:
    path: "/mnt/{{ gluster_volume_name }}"
    src: "localhost:/{{ gluster_volume_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
