---
- name: Verify Gluster dependencies
  ansible.builtin.apt:
    pkg:
      - xfsprogs
      - attr
      - glusterfs-common
      - glusterfs-client
    state: present
    force_apt_get: true
    update_cache: true

- name: Create GlusterFS mount directory
  ansible.builtin.file:
    path: "/mnt/{{ gluster_volume_name }}"
    state: directory

- name: Mount GlusterFS volume
  ansible.posix.mount:
    path: "/mnt/{{ gluster_volume_name }}"
    src: "localhost:/{{ gluster_volume_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
