---
- name: Reconfigure package cloud-init
  debconf:
    name: cloud-init

- name: Delete cloud-init packages
  apt:
    name: cloud-init
    state: absent

- name: Recursively remove directory /etc/cloud/
  file:
    path: /etc/cloud/
    state: absent

- name: Recursively remove directory /var/lib/cloud/
  file:
    path: /var/lib/cloud/
    state: absent

- name: Disable swapping
  shell: swapoff --all
  register: task_result

- name: Check if auto update is enabled
  stat:
    path: /etc/apt/apt.conf.d/20auto-upgrades
  register: autoupdate

- name: Disable auto update
  file:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    state: absent
  when: autoupdate.stat.exists

- name: Wait for any possibly running unattended upgrade to finish
  raw: >-
    systemd-run --property="After=apt-daily.service apt-daily-upgrade.service"
    --wait /bin/true
  when: autoupdate.stat.exists

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Upgrade all packages to the latest version
  apt:
    force_apt_get: yes
    name: "*"
    state: latest
    update_cache: yes

- name: Disable IPv6 in sysctl.conf
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Ensure sysctl.conf is updated
  command: sysctl -p

- name: Disable IPv6 in GRUB configuration
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="ipv6.disable=1"'
    state: present

- name: Update GRUB configuration
  command: update-grub
  
- name: Reboot immediately if there was a change
  shell: sleep 2 && /sbin/shutdown -r now "ansible reboot request"
  async: 1
  poll: 0
  when: task_result.changed

- name: Wait for the reboot to complete if there was a change
  wait_for_connection:
    connect_timeout: 20
    delay: 5
    sleep: 5
    timeout: 300
  when: task_result.changed

- name: Verify system dependencies
  apt:
    force_apt_get: yes
    name:
      - aptitude
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - apache2-utils
      - tree
      - wget
      - curl
      - tcpdump
      - python3-docker
      - ntp
      - lsb-release
    state: latest
    update_cache: yes
