---
# ============================
# Update APT Cache
# ============================
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

# ============================
# Install Fish Shell
# ============================
- name: Install Fish shell
  ansible.builtin.apt:
    name: fish
    state: present

# ============================
# Change Default Shell to Fish
# ============================
- name: Change default shell to Fish
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /usr/bin/fish

- name: Verify default shell for the user
  ansible.builtin.shell: >
    set -o pipefail &&  getent passwd "{{ target_user }}" | cut -d: -f7
  args:
    executable: /bin/bash
  register: user_shell
  changed_when: false

- name: Display default shell
  ansible.builtin.debug:
    msg: "Default shell for {{ target_user }} is {{ user_shell.stdout }}"

- name: Ensure Fish is set as the default shell
  ansible.builtin.assert:
    that:
      - user_shell.stdout == "/usr/bin/fish"
    fail_msg: "Fish is not set as the default shell for {{ target_user }}!"
    success_msg: "Fish is successfully set as the default shell for {{ target_user }}!"
