---
- name: Check if Swarm is Already Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- debug: var=hostvars[groups['swarm_managers'][0]]['worker_token']['stdout']

- name: Add Workers to the Swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ hostvars[groups['swarm_managers'][0]]['worker_token']['stdout'] }}"
    remote_addrs: "{{ hostvars[groups['swarm_managers'][0]]['ansible_default_ipv4']['address'] }}:2377"
  when: swarm_status.rc != 0 