---
- name: Get Docker key
  apt_key:
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    state: present
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: Add Docker packages to Repository
  apt_repository:
    repo: >-
      deb [arch=amd64] https://download.docker.com/linux/ubuntu {{
      ansible_distribution_release|lower }} stable
    state: present

- name: Verify Docker dependencies
  apt:
    force_apt_get: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Appending the group docker
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install Docker Compose if not exist
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Change Docker Compose permission
  file:
    path: /usr/local/bin/docker-compose
    group: docker
    mode: '0750'
