---
- name: Set system timezone to {{ tz }}
  ansible.builtin.command: timedatectl set-timezone {{ tz }}
  changed_when: false
  check_mode: false

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_repo_url }}"
    state: present

- name: Install Docker dependencies
  ansible.builtin.apt:
    force_apt_get: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: true

- name: Install Docker packages
  ansible.builtin.apt:
    force_apt_get: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Add user 'ubuntu' to the docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true

- name: Check if Docker Compose is already installed
  ansible.builtin.stat:
    path: "{{ docker_compose_path }}"
  register: docker_compose_stat

- name: Download Docker Compose binary
  ansible.builtin.get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: "0755"
  when: not docker_compose_stat.stat.exists

- name: Set Docker Compose permissions
  ansible.builtin.file:
    path: "{{ docker_compose_path }}"
    owner: root
    group: docker
    mode: "0755"
  when: not docker_compose_stat.stat.exists

- name: Verify Docker service is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Verify Docker Compose version
  ansible.builtin.command: "{{ docker_compose_path }} --version"
  register: docker_compose_version_result
  changed_when: false

- name: Display Docker Compose version
  ansible.builtin.debug:
    msg: "Docker Compose version: {{ docker_compose_version_result.stdout }}"
